---
- name: Ensure MariaDB certificate directory exists
  become: true
  file:
    state: directory
    path: "{{ node_config_directory }}/mariadb-certs"
    mode: "0775"

- name: Copying over extra CA certificates
  become: true
  vars:
    service: "{{ mariadb_services['mariadb'] }}"
  copy:
    src: "{{ kolla_certificates_dir }}/ca/"
    dest: "{{ node_config_directory }}/mariadb-certs/ca-certificates"
    mode: "0644"
  when:
    - kolla_copy_ca_into_containers | bool
    - service | service_enabled_and_mapped_to_host
  notify:
    - Restart mariadb container

- name: Copying over TLS certificate
  become: true
  vars:
    service: "{{ mariadb_services['mariadb'] }}"
  copy:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/mariadb-certs/mariadb-cert.pem"
    mode: "0644"
  with_first_found:
    - files:
        - "{{ kolla_certificates_dir }}/{{ inventory_hostname }}/{{ mariadb_tls_cert }}"
        - "{{ kolla_certificates_dir }}/{{ inventory_hostname }}-cert.pem"
        - "{{ kolla_certificates_dir }}/{{ mariadb_tls_cert }}"
      skip: true
  when:
    - service | service_enabled_and_mapped_to_host
  notify:
    - Restart mariadb container

- name: Copying over TLS key
  become: true
  vars:
    service: "{{ mariadb_services['mariadb'] }}"
  copy:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/mariadb-certs/mariadb-key.pem"
    mode: "0644"
  with_first_found:
    - files:
        - "{{ kolla_certificates_dir }}/{{ inventory_hostname }}/{{ mariadb_tls_key }}"
        - "{{ kolla_certificates_dir }}/{{ inventory_hostname }}-key.pem"
        - "{{ kolla_certificates_dir }}/{{ mariadb_tls_key }}"
      skip: true
  when:
    - service | service_enabled_and_mapped_to_host
  notify:
    - Restart mariadb container