---
- name: Ensuring private MariaDB directory exist
  file:
    path: "{{ mariadb_dir }}"
    state: "directory"
    mode: "0770"

- name: Creating MariaDB SSL configuration file
  template:
    src: "{{ item }}.j2"
    dest: "{{ kolla_certificates_dir }}/{{ item }}"
    mode: "0660"
  with_items:
    - "openssl-kolla-mariadb.cnf"

- name: Creating MariaDB Server Certificate key
  command: >
    openssl genrsa
    -out "{{ mariadb_dir }}/mariadb.key" 2048
  args:
    creates: "{{ kolla_tls_mariadb_key }}"

- name: Creating MariaDB Server Certificate signing request
  command: >
    openssl req
    -new
    -key "{{ mariadb_dir }}/mariadb.key"
    -out "{{ mariadb_dir }}/mariadb.csr"
    -config "{{ kolla_certificates_dir }}/openssl-kolla-mariadb.cnf"
    -sha256
  args:
    creates: "{{ mariadb_dir }}/mariadb.csr"

- name: Creating MariaDB Server Certificate
  command: >
    openssl x509
    -req
    -in "{{ mariadb_dir }}/mariadb.csr"
    -CA "{{ root_dir }}/root.crt"
    -CAkey "{{ root_dir }}/root.key"
    -CAcreateserial
    -extensions v3_req
    -extfile "{{ kolla_certificates_dir }}/openssl-kolla-mariadb.cnf"
    -out "{{ mariadb_dir }}/mariadb.crt"
    -days 500
    -sha256
  args:
    creates: "{{ mariadb_dir }}/mariadb.crt"

- name: Setting permissions on MariaDB key
  file:
    path: "{{ mariadb_dir }}/mariadb.key"
    mode: "0660"
    state: file

- name: Copy MariaDB cert to default configuration location
  copy:
    src: "{{ mariadb_dir }}/mariadb.crt"
    dest: "{{ kolla_certificates_dir }}/mariadb-cert.pem"
    mode: "0660"

- name: Copy MariaDB key to default configuration location
  copy:
    src: "{{ mariadb_dir }}/mariadb.key"
    dest: "{{ kolla_certificates_dir }}/mariadb-key.pem"
    mode: "0660"
