---
- import_role:
    name: service-precheck
  vars:
    service_precheck_services: "{{ frr_services }}"
    service_name: "{{ project_name }}"

- name: Get container facts
  become: true
  kolla_container_facts:
    action: get_containers
    container_engine: "{{ kolla_container_engine }}"
    name:
      - frr
  register: container_facts
